### ISSUE TITLE
smali plugin

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-plugins#2]
https://github.com/lucasduffey/smaliBinja_python

still in active development, but I want to try to get it using the official plugin.json stuff

**Comment by lucasduffey** [comment]
the "PluginName" link @ https://github.com/Vector35/binaryninja-plugins/blob/master/plugins/README.md redirects to the wrong place.

should be https://github.com/lucasduffey/smaliBinja-python/


Should there be a field in the plugin.json for the url? Or should that be baked into your system?

**Comment by psifertex** [comment]
I'd like to bake the correct URL in -- specifically the snapshot that was checked in, looking into that now.

**Comment by lucasduffey** [comment]
would it make sense to pull master?

**Comment by psifertex** [comment]
Submodules automatically pull from master, but to update it after that requires manually pulling in the latest version. At any given moment there is always only a specific revision being linked to. 

I might just update the script to always link to the main github page which is probably easiest for now.

**Comment by lucasduffey** [comment]
maybe it would make sense to drop the submodules and the client iterate over their plugin list and do "git pulls" using python's git api on each repo.

**Comment by psifertex** [comment]
Now fixed -- script creates the url based on the github page directly.
