### ISSUE TITLE
FLIRT plugin

### ISSUE THREAD

**Issue by kenoph** [Vector35/binaryninja-plugins#22]
[https://github.com/kenoph/nampa](https://github.com/kenoph/nampa)

(When I have some time I want to split the repo into the python module and the binary ninja plugin, but for now it works as it is)

**Comment by psifertex** [comment]
Sorry for missing this! Great plugin, note that all the plugins have been moved over to the [community-plugins](/Vector35/community-plugins/) repo. Add it there now.
