### ISSUE TITLE
Syscall identifers plugin

### ISSUE THREAD

**Issue by HascoetKevin** [Vector35/binaryninja-plugins#23]
Hi ! 
I propose to add my plugin to identify syscalls in the community plugins repository.. 
I know it is pretty basic so I don't know if it worth to be shared , but I try !
There is the url : https://github.com/HascoetKevin/SyscallsIdentifier_BinaryNinja

Thanks !
Have a good day !

**Comment by psifertex** [comment]
Thanks! I've added your plugin.

FYI, I need to remove this repository -- it's deprecated in favor of [/Vector35/community-plugins/](/Vector35/community-plugins/)
