### ISSUE TITLE
Custom Hook plugin

### ISSUE THREAD

**Issue by orndorffgrant** [Vector35/binaryninja-plugins#24]
https://github.com/orndorffgrant/bnhook

Currently, you can overwrite existing code. This allows insertion of additional code. Uses extra space present in ELF format. Written to be fairly easy to extend to other architectures and executable formats.

Learned a lot while writing it; hopefully you think its useful!

**Comment by psifertex** [comment]
Nice, thanks! We've actually got an open bug for "smart patching" to do that in the main product, but this looks to hit many of the same features.

Also, note that the new repo for plugins is over on [community-plugins](/Vector35/community-plugins/). I really need to update the main readme here.

I'll push this as a submodule over there shortly. Thanks!
